version: '3.5'
services:
  database:
    container_name: das-postgres
    image: postgres
    ports:
      - 35432:5432
    environment:
      - POSTGRES_USER=pedidos
      - POSTGRES_PASSWORD=pedidos123
      - POSTGRES_DB=pedidos
    restart: unless-stopped

  pgadmin:
    container_name: das-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - database
  
  api:
    container_name: das-api
    build: ./backend/
    image: das-angular/api
    ports:
      - 8090:8090
    depends_on:
      - database
  
  web:
    container_name: das-web
    build: ./frontend/
    image: das-angular/web
    ports:
      - 4200:80
    depends_on:
      - api
    