server:
  port: 8090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:35432/pedidos}
    username: ${JDBC_DATABASE_USERNAME:pedidos}
    password: ${JDBC_DATABASE_PASSWORD:pedidos123}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect