server:
  port: 8090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql:pedidos
    username: pedidos
    password: pedidos123
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect