server:
  port: 8090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:apidb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true